services:
  postgres:
    image: postgres:latest
    container_name: clinica_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-clinica_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-clinica_password}
      POSTGRES_DB: ${POSTGRES_DB:-clinica_db}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: